# Site settings
title: Clinical Genomics customer portal
email: robin.andeer@scilifelab.se
description: >
  Public customer portal at SciLifeLab Clinical Genomics.
baseurl: ""
url: "http://www.clinicalgenomics.se"

collections:
  topics:
    output: true
  team:
    output: true

# Build settings
markdown: kramdown
permalink: pretty
sass:
  sass_dir: _scss
exclude: ["node_modules"]

page_gen-dirs: true # uncomment, if you prefer to generate named folders
page_gen:
  - data: analyses
    template: analysis
    name: code
    dir: analyser
