# Site settings
title: Clinical Genomics customer portal
email: robin.andeer@scilifelab.se
description: >
  Public customer portal at SciLifeLab Clinical Genomics.
baseurl: ""
url: "http://www.clinicalgenomics.se"

navigation:
  - label: Ordrar
    url: /ordrar/
  - label: Analyser
    url: /analyser/
  - label: Dataleveranser
    url: /dataleveranser/
  - label: Krav på prover
    url: /provkrav/
  - label: Support och kontakt
    url: /support-kontakt/
  - label: Biblioteksprepp och sekvensering
    url: /bibliotek-sekvensering/

# Build settings
markdown: kramdown
permalink: pretty
sass:
  sass_dir: _sass
exclude: ['node_modules']
