# Site settings
title: Clinical Genomics customer portal
email: robin.andeer@scilifelab.se
description: >
  Public customer portal at SciLifeLab Clinical Genomics.
baseurl: ""
url: "http://www.clinicalgenomics.se"

navigation:
  - label: Ordering
    url: /ordering/
  - label: Analyses
    url: /analyses/
  - label: Data delivery
    url: /data-delivery/
  - label: Sample requirements
    url: /sample-requirements/
  - label: Support and contact
    url: /support-contact/
  - label: Library preparation and sequencing
    url: /library-sequencing/

# Build settings
markdown: kramdown
permalink: pretty
sass:
  sass_dir: _sass
exclude: ['node_modules']
