# Site settings
title: Clinical Genomics customer portal
email: robin.andeer@scilifelab.se
description: >
  Public customer portal at SciLifeLab Clinical Genomics.
baseurl: ""
url: "http://www.clinicalgenomics.se"

navigation:
  - label: Beställningar
    url: /beställningar/
  - label: Analyser
    url: /analyser/
  - label: Dataleverans
    url: /dataleverans/
  - label: Krav på prover
    url: /provkrav/
  - label: Kontakt
    url: /kontakt/

# Build settings
markdown: kramdown
permalink: pretty
sass:
  sass_dir: _sass
exclude: ["node_modules"]
